const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/data/products.ts');

const content = `import { Product } from '../types/product';

export const PRODUCTS: Product[] = [
{
    id: 'prod-1',
    name: 'Santa Maria Grill Small',
    category: 'Santa Maria Series',
    price: 45000,
    featured: true,
    image: '/images/products/10_Visualise Files -Santa Maria Grill Small/SantaMaria BBQ Meduim- Paint Model 1.jpg',
    images: ["/images/products/10_Visualise Files -Santa Maria Grill Small/SantaMaria BBQ Meduim- Paint Model 1.jpg","/images/products/10_Visualise Files -Santa Maria Grill Small/SantaMaria BBQ Meduim- Paint Model 2.jpg","/images/products/10_Visualise Files -Santa Maria Grill Small/SantaMaria BBQ Meduim- Paint Model 3.jpg"],
    video: '/images/products/10_Visualise Files -Santa Maria Grill Small/SantaMaria BBQ Meduim- Paint Model 4.1.mp4',
    description: 'Industrial grade wood-fired grill for authentic BBQ.',
    features: ['Adjustable Grate', 'Wood-Fired Flavour', 'Heavy Duty Base'],
    specifications: { 'Material': 'Stainless Steel', 'Size': 'Small' },
},
{
    id: 'prod-2',
    name: 'Suitcase BBQ Big',
    category: 'Suitcase BBQ',
    price: 7500,
    featured: true,
    image: '/images/products/11_Visualise Files - Suitcase BBQ Big/1_Suitcase BBQ Big Painted 4.jpg',
    images: ["/images/products/11_Visualise Files - Suitcase BBQ Big/1_Suitcase BBQ Big Painted 4.jpg","/images/products/11_Visualise Files - Suitcase BBQ Big/2_Suitcase BBQ Big Painted 5.jpg","/images/products/11_Visualise Files - Suitcase BBQ Big/3_Suitcase BBQ Big Painted 2.jpg"],
    video: '/images/products/11_Visualise Files - Suitcase BBQ Big/1_Suitcase BBQ Big Painted 3.mp4',
    description: 'Portable large suitcase BBQ for camping.',
    features: ['Portable Design', 'Easy Cleanup', 'Large Cooking Area'],
    specifications: { 'Material': 'Painted Steel', 'Size': 'Large' },
},
{
    id: 'prod-3',
    name: 'Suitcase BBQ Small',
    category: 'Suitcase BBQ',
    price: 5000,
    featured: true,
    image: '/images/products/12_Visualise Files - Suitcase BBQ Small/Suitcase BBQ Small - Paint Model 2.jpg',
    images: ["/images/products/12_Visualise Files - Suitcase BBQ Small/Suitcase BBQ Small - Paint Model 2.jpg","/images/products/12_Visualise Files - Suitcase BBQ Small/Suitcase BBQ Small - Paint Model 3.jpg","/images/products/12_Visualise Files - Suitcase BBQ Small/Suitcase BBQ Small - Paint Model 4.jpg","/images/products/12_Visualise Files - Suitcase BBQ Small/Suitcase BBQ Small - Paint Model.jpg"],
    video: '/images/products/12_Visualise Files - Suitcase BBQ Small/Suitcase BBQ Small - Paint Model 5.mp4',
    description: 'Compact and fully portable suitcase BBQ.',
    features: ['Ultra Compact', 'Lightweight', 'High Heat Output'],
    specifications: { 'Material': 'Painted Steel', 'Size': 'Small' },
},
{
    id: 'prod-4',
    name: 'Flip BBQ Standard Base',
    category: 'Collapsible BBQ',
    price: 12500,
    featured: true,
    image: '/images/products/1_Visualise Files - Flip Base/Flip BBQ with Standard Base V1 2.png',
    images: ["/images/products/1_Visualise Files - Flip Base/Flip BBQ with Standard Base V1 2.png","/images/products/1_Visualise Files - Flip Base/Flip BBQ with Standard Base V1 3.png","/images/products/1_Visualise Files - Flip Base/Flip BBQ with Standard Base V1 4.png","/images/products/1_Visualise Files - Flip Base/Flip BBQ with Standard Base V2.png","/images/products/1_Visualise Files - Flip Base/Flip BBQ with Standard Base V3.png"],
    video: '/images/products/1_Visualise Files - Flip Base/Flip BBQ with Standard Base V1.mp4',
    description: 'Innovative flip mechanism with standard industrial base.',
    features: ['Flip Mechanism', 'Even Cooking', 'Sturdy Base'],
    specifications: { 'Material': 'Stainless Steel', 'Mechanism': 'Flip' },
},
{
    id: 'prod-5',
    name: 'Flip BBQ Height Adjustable',
    category: 'Collapsible BBQ',
    price: 15000,
    featured: false,
    image: '/images/products/2_Visualise Files - Flip Base Height Adjustable/Flip Height Adjustable Open Model Pint 3.png',
    images: ["/images/products/2_Visualise Files - Flip Base Height Adjustable/Flip Height Adjustable Open Model Pint 3.png","/images/products/2_Visualise Files - Flip Base Height Adjustable/Flip Height Adjustable Pinted 2.png","/images/products/2_Visualise Files - Flip Base Height Adjustable/Flip Height Adjustable Pinted 3.png","/images/products/2_Visualise Files - Flip Base Height Adjustable/Flip Height Adjustable Pinted 4.png"],
    video: '/images/products/2_Visualise Files - Flip Base Height Adjustable/Flip Height Adjustable Open Model Pint 4.mp4',
    description: 'Premium Flip BBQ with fully adjustable height base.',
    features: ['Height Adjustable Base', 'Flip Grill Design', 'Premium Build'],
    specifications: { 'Material': 'Stainless Steel', 'Height': 'Adjustable' },
},
{
    id: 'prod-6',
    name: 'Collapsible BBQ Large',
    category: 'Collapsible BBQ',
    price: 12000,
    featured: false,
    image: '/images/products/3_Visualise Files - Collapsible_BBQ/Coal Jug 3.png',
    images: ["/images/products/3_Visualise Files - Collapsible_BBQ/Coal Jug 3.png","/images/products/3_Visualise Files - Collapsible_BBQ/Coal Jug 4.png","/images/products/3_Visualise Files - Collapsible_BBQ/Collapasible Big with Grill Plate.png","/images/products/3_Visualise Files - Collapsible_BBQ/Collapasible Big with Hot Plate.png","/images/products/3_Visualise Files - Collapsible_BBQ/Untitled Project.png"],
    video: '/images/products/3_Visualise Files - Collapsible_BBQ/1_Collapasible Big SS Model 2.mp4',
    description: 'Large heavy-duty collapsible BBQ for commercial spaces.',
    features: ['High Capacity', 'Foldable Legs', 'Heavy Duty'],
    specifications: { 'Material': 'Stainless Steel', 'Type': 'Collapsible' },
},
{
    id: 'prod-7',
    name: 'Collapsible Flip Combo',
    category: 'Collapsible BBQ',
    price: 24500,
    featured: false,
    image: '/images/products/4_Visualise Files  - Collapsible_Flip/Collapsible BBQ and Flip 2.jpg',
    images: ["/images/products/4_Visualise Files  - Collapsible_Flip/Collapsible BBQ and Flip 2.jpg","/images/products/4_Visualise Files  - Collapsible_Flip/Collapsible BBQ and Flip 3.jpg","/images/products/4_Visualise Files  - Collapsible_Flip/Collapsible BBQ and Flip 4.jpg","/images/products/4_Visualise Files  - Collapsible_Flip/Collapsible BBQ and Flip 5.jpg"],
    video: '/images/products/4_Visualise Files  - Collapsible_Flip/Collapsible BBQ and Flip 6.mp4',
    description: 'Ultimate combination of the collapsible frame and flip grill.',
    features: ['Combo Unit', 'Ultimate Flexibility', 'Easy Setup'],
    specifications: { 'Material': 'Stainless Steel', 'Combo': 'Yes' },
},
{
    id: 'prod-8',
    name: 'Collapsible BBQ Small',
    category: 'Collapsible BBQ',
    price: 6200,
    featured: false,
    image: '/images/products/5_Visualise Files  - Collapsible_BBQ Small/Collapsible BBQ Small - Paint Version 2.jpg',
    images: ["/images/products/5_Visualise Files  - Collapsible_BBQ Small/Collapsible BBQ Small - Paint Version 2.jpg","/images/products/5_Visualise Files  - Collapsible_BBQ Small/Collapsible BBQ Small - Paint Version 3.jpg","/images/products/5_Visualise Files  - Collapsible_BBQ Small/Collapsible BBQ Small - Paint Version 4.jpg","/images/products/5_Visualise Files  - Collapsible_BBQ Small/Collapsible BBQ Small - Paint Version 5.jpg","/images/products/5_Visualise Files  - Collapsible_BBQ Small/Collapsible BBQ Small - Paint Version 6.jpg","/images/products/5_Visualise Files  - Collapsible_BBQ Small/Collapsible BBQ Small - Paint Version 7.jpg"],
    description: 'Small footprint collapsible BBQ perfect for outdoor spaces.',
    features: ['Small Footprint', 'Collapsible', 'Quick Heating'],
    specifications: { 'Material': 'Painted Steel', 'Type': 'Collapsible Small' },
},
{
    id: 'prod-9',
    name: 'Rocket Stove 150MM',
    category: 'Rocket Stoves',
    price: 3499,
    featured: false,
    image: '/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove 150MM Painted Model 2.jpg',
    images: ["/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove 150MM Painted Model 2.jpg","/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove 150MM Painted Model 3.jpg","/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove 150MM Painted Model 4.jpg","/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove 150MM Painted Model 6.jpg","/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove 150MM Painted Model 7.jpg","/images/products/6_Visualise Files - Rocket Stove_150MM/Rocket Stove 150MM Painted Model 8.jpg"],
    video: '/images/products/6_Visualise Files - Rocket Stove_150MM/1_Rocket Stove 150MM Painted Model 5.mp4',
    description: 'High efficiency 150mm rocket stove.',
    features: ['Efficiency Burner', '150MM Output', 'Heat Focused'],
    specifications: { 'Material': 'Painted Steel', 'Size': '150MM' },
},
{
    id: 'prod-10',
    name: 'Rocket Stove Collapsible',
    category: 'Rocket Stoves',
    price: 4200,
    featured: false,
    image: '/images/products/7_Visualise Files - Rocket Stove_Collapsible/Rocket Stove Collapsible Small 2.jpg',
    images: ["/images/products/7_Visualise Files - Rocket Stove_Collapsible/Rocket Stove Collapsible Small 2.jpg","/images/products/7_Visualise Files - Rocket Stove_Collapsible/Rocket Stove Collapsible Small 3.jpg","/images/products/7_Visualise Files - Rocket Stove_Collapsible/Rocket Stove Collapsible Small 4.jpg","/images/products/7_Visualise Files - Rocket Stove_Collapsible/Rocket Stove Collapsible Small 5.jpg","/images/products/7_Visualise Files - Rocket Stove_Collapsible/Rocket Stove Collapsible Small 6.jpg"],
    video: '/images/products/7_Visualise Files - Rocket Stove_Collapsible/Rocket Stove Collapsible Small 7.mp4',
    description: 'Easily transportable collapsible rocket stove.',
    features: ['Collapsible Design', 'Fuel Efficient', 'Backpacking Ready'],
    specifications: { 'Material': 'Painted Steel', 'Type': 'Collapsible' },
},
{
    id: 'prod-11',
    name: 'Automatic BBQ',
    category: 'Automatic BBQ',
    price: 12999,
    featured: false,
    image: '/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ Paint Model V2.png',
    images: ["/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ Paint Model V2.png","/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ Paint Model.png","/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ SS Model 2.png","/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ SS Model 3.png","/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ SS Model 4.png","/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ SS Model 5.png","/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ SS Model 6.png","/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ SS Model 7.png"],
    video: '/images/products/8_Visualise Renders  - Automatic BBQ/Automatic BBQ SS Model.mp4',
    description: 'Industrial grade automatic rotisserie BBQ.',
    features: ['Automated Grilling', 'Even Heat Distribution', 'Rotisserie Setup'],
    specifications: { 'Material': 'Stainless/Painted', 'Automation': 'Yes' },
},
{
    id: 'prod-12',
    name: 'Santa Maria Grill Medium',
    category: 'Santa Maria Series',
    price: 55000,
    featured: false,
    image: '/images/products/9_Visualise Files -Santa Maria Grill Medium/SantaMaria BBQ Meduim- Paint Model 1.jpg',
    images: ["/images/products/9_Visualise Files -Santa Maria Grill Medium/SantaMaria BBQ Meduim- Paint Model 1.jpg","/images/products/9_Visualise Files -Santa Maria Grill Medium/SantaMaria BBQ Meduim- Paint Model 2.jpg","/images/products/9_Visualise Files -Santa Maria Grill Medium/SantaMaria BBQ Meduim- Paint Model 3.jpg"],
    video: '/images/products/9_Visualise Files -Santa Maria Grill Medium/SantaMaria BBQ Meduim- Paint Model 4.mp4',
    description: 'Medium sized professional Santa Maria Grill with adjustable grate.',
    features: ['Adjustable Grate Height', 'Wood Fire Pan', 'Medium Pro Size'],
    specifications: { 'Material': 'Stainless/Painted', 'Size': 'Medium' },
}
];
`;
fs.writeFileSync(filePath, content);
console.log('Fixed products2.ts');
